[package]
name = "rgch"
version = "0.1.4"
authors = ["Scstechr <teufelkonig@gmail.com>"]
edition = "2018"
description = "Rust version of gch"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
termios = "0.3.1"
