pub const X: &str = "\x1b[m"; // Reset
pub const S: &str = "\x1b[1m"; // Strengthen. Bold.
pub const U: &str = "\x1b[4m"; // Underline.
pub const W: &str = "\x1b[30m"; // Weak (almost gone)
pub const F: &str = "\x1b[90m"; // Fade
pub const R: &str = "\x1b[91m"; // Red
pub const G: &str = "\x1b[92m"; // Green
pub const B: &str = "\x1b[94m"; // Blue
pub const C: &str = "\x1b[96m"; // Cyan
